routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::prefix('admin')->as('admin.')->namespace('Admin')->middleware('auth')->group(function () {
    Route::resource('types', 'TypeController');
    Route::resource('specialities', 'SpecialityController');
    Route::resource('texts', 'TextController');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/', 'TextController@index');
Route::get('{year}/{number}', 'TextController@show');

app/Speciality.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Speciality extends Model
{
    protected $fillable = [
        'name'
    ];

    public $timestamps = false;

    public function text ()
    {
        return $this->hasMany('App\Text');
    }
}

app/Text.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Text extends Model
{
    protected $fillable = [
        'type_id', 'number', 'year', 'body', 'speciality_id'
    ];

    public $timestamps = false;

    public function type()
    {
        return $this->belongsTo('App\Type');
    }

    public function speciality()
    {
        return $this->belongsTo('App\Speciality');
    }
}

app/Type.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Type extends Model
{
    protected $fillable = [
        'name'
    ];

    public $timestamps = false;

    public function text ()
    {
        return $this->hasMany('App\Text');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/SpecialityController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Speciality;

class SpecialityController extends Controller
{
    public function index()
    {
        $specialities = Speciality::all();

        return view('admin.specialities.index', compact('specialities'));
    }

    public function create()
    {
        return view('admin.specialities.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name'  =>  'required'
        ]);

        Speciality::create($request->all());

        return redirect()->route('admin.specialities.index');
    }
}

app/Http/Controllers/Admin/TextController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Text;

class TextController extends Controller
{
    public function index()
    {
        $texts = Text::all();

        return view('admin.texts.index', compact('texts'));
    }

    public function create()
    {
        return view('admin.texts.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'number'    =>  'required|numeric',
            'year'      =>  'required|numeric',
            'type_id'   =>  'required|exists:types,id',
            'speciality_id'   =>  'required|exists:specialities,id',
            'body'      =>  'required',
        ]);

        Text::create($request->all());

        return redirect()->route('admin.texts.index');
    }
}

app/Http/Controllers/Admin/TypeController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Type;

class TypeController extends Controller
{
    public function index()
    {
        $types = Type::all();

        return view('admin.types.index', compact('types'));
    }

    public function create()
    {
        return view('admin.types.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name'  =>  'required'
        ]);

        Type::create($request->all());

        return redirect()->route('admin.types.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TextController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Text;

class TextController extends Controller
{
    public function index(Request $request)
    {
        $texts = Text::query();

        if ($request->keyword) {
            $texts->where('body', 'LIKE', '%' . $request->keyword . '%');
        }

        if ($request->number) {
            $texts->where('number', $request->number);
        }

        if ($request->year_from) {
            $texts->where('year', '>', $request->year_from);
        }

        if ($request->year_until) {
            $texts->where('year', '<', $request->year_until);
        }

        if ($request->type_id) {
            $texts->where('type_id', $request->type_id);
        }

        if ($request->speciality_id) {
            $texts->where('speciality_id', $request->speciality_id);
        }

        $texts = $texts->get();

        return view('texts.index', compact('texts'));
    }

    public function show($year, $number)
    {
        $text = Text::where(compact('year', 'number'))->firstOrFail();

        return view('texts.show', compact('text'));
    }
}

resources/views/admin/specialities/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">إضافة تخصص</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('admin.specialities.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">الإسم</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    إضافة
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/specialities/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group text-left">
                <a class="btn btn-primary" href="{{ route('admin.specialities.create') }}">إضافة تخصص</a>
            </div>

            @if (count($specialities))
                <div class="panel panel-default">
                    <div class="panel-heading">التخصصات</div>

                        <div class="panel-body">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>اسم الصنف</th>
                                        <th>خيارات</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($specialities as $item)
                                        <tr>
                                            <td>{{ $item->id }}</td>
                                            <td>{{ $item->name }}</td>
                                            <td>...</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>

                </div>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/admin/texts/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">إضافة نص</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('admin.texts.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('number') ? ' has-error' : '' }}">
                            <label for="number" class="col-md-3 control-label">رقم</label>

                            <div class="col-md-7">
                                <input id="number" type="number" class="form-control" name="number" value="{{ old('number') }}" required autofocus>

                                @if ($errors->has('number'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('number') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('year') ? ' has-error' : '' }}">
                            <label for="year" class="col-md-3 control-label">سنة الإصدار</label>

                            <div class="col-md-7">
                                <select class="form-control" name="year">
                                    <option value="" selected disabled>-- سنة الإصدار --</option>
                                    @foreach (range(date('Y'), 1900) as $year)
                                        <option value="{{ $year }}">{{ $year }}</option>
                                    @endforeach
                                </select>

                                @if ($errors->has('year'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('year') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('type_id') ? ' has-error' : '' }}">
                            <label for="type_id" class="col-md-3 control-label">الصنف</label>

                            <div class="col-md-7">
                                <select class="form-control" name="type_id">
                                    <option value="" disabled selected>-- اختر صنف --</option>
                                    @foreach ($types as $type)
                                        <option value="{{ $type->id }}">{{ $type->name }}</option>
                                    @endforeach
                                </select>

                                @if ($errors->has('type_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('type_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('speciality_id') ? ' has-error' : '' }}">
                            <label for="speciality_id" class="col-md-3 control-label">التخصص</label>

                            <div class="col-md-7">
                                <select class="form-control" name="speciality_id">
                                    <option value="" disabled selected>-- اختر تخصص --</option>
                                    @foreach ($specialities as $speciality)
                                        <option value="{{ $speciality->id }}">{{ $speciality->name }}</option>
                                    @endforeach
                                </select>

                                @if ($errors->has('speciality_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('speciality_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
                            <label for="body" class="col-md-3 control-label">المحتوى</label>

                            <div class="col-md-7">
                                <textarea name="body" rows="20" class="form-control">{{ old('body') }}</textarea>

                                @if ($errors->has('body'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('body') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-7 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    إضافة
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/texts/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group text-left">
                <a class="btn btn-primary" href="{{ route('admin.texts.create') }}">إضافة نص</a>
            </div>

            @if (count($texts))
                <div class="panel panel-default">
                    <div class="panel-heading">النصوص</div>

                        <div class="panel-body">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>العنوان</th>
                                        <th>التخصص</th>
                                        <th>خيارات</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($texts as $text)
                                        <tr>
                                            <td>{{ $text->id }}</td>
                                            <td>{{ $text->type->name }} رقم {{ $text->number }} لسنة {{ $text->year }}</td>
                                            <td>{{ $text->speciality->name }}</td>
                                            <td>...</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>

                </div>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/admin/types/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">إضافة صنف</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('admin.types.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">الإسم</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    إضافة
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/types/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group text-left">
                <a class="btn btn-primary" href="{{ route('admin.types.create') }}">إضافة صنف</a>
            </div>

            @if (count($types))
                <div class="panel panel-default">
                    <div class="panel-heading">الأصناف</div>

                        <div class="panel-body">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>اسم الصنف</th>
                                        <th>خيارات</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($types as $type)
                                        <tr>
                                            <td>{{ $type->id }}</td>
                                            <td>{{ $type->name }}</td>
                                            <td>...</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>

                </div>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">لوحة التحكم</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    لقد قمت بتسجيل الدخول
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>لوحة التحكم</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Load Bootstrap RTL theme from RawGit -->
    <link rel="stylesheet" href="//cdn.rawgit.com/morteza/bootstrap-rtl/v3.3.4/dist/css/bootstrap-rtl.min.css">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/home') }}">
                        لوحة التحكم
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        @if (Auth::user())
                            <li>
                                <a href="{{ route('admin.types.index') }}">الأصناف</a>
                            </li>
                            <li>
                                <a href="{{ route('admin.specialities.index') }}">التخصصات</a>
                            </li>
                            <li>
                                <a href="{{ route('admin.texts.index') }}">النصوص</a>
                            </li>
                        @endif
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-left">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">دخول</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            خروج
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                    <li>
                                        <a href="{{ url('/') }}">الصفحة الرئيسية</a>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/home.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>موسوعة التشريعات الليبية</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Load Bootstrap RTL theme from RawGit -->
    <link rel="stylesheet" href="//cdn.rawgit.com/morteza/bootstrap-rtl/v3.3.4/dist/css/bootstrap-rtl.min.css">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        موسوعة التشريعات الليبية
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-left">
                        <!-- Authentication Links -->
                        <li><a href="{{ route('login') }}">دخول</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/texts/show.blade.php
@extends('layouts.home')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            @if ($text)
                <div class="panel panel-default">
                    <div class="panel-heading">{{ $text->type->name }} رقم {{ $text->number }} لسنة {{ $text->year }}</div>

                        <div class="panel-body">
                            {!! str_replace(request()->keyword, '&#x200d;<span style="background-color:yellow;">' . request()->keyword . '&#x200d;</span>', nl2br($text->body)) !!}
                        </div>

                </div>
            @endif
        </div>
    </div>
</div>
@endsection